apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/address-pool: external-pool
  name: nginx-mlb-l2-service
spec:
  allocateLoadBalancerNodePorts: true
  selector:
    app: nginx-lbl2
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 10.131.2.14
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.131.2.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-metalb
  namespace: metallb-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    
    
    events {
        worker_connections  1024;
    }
    
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        access_log  /var/log/nginx/access.log  main;
    
            server {
                listen       8080;
                server_name  localhost;
    
                location / {
                    return 200 "\n Welcome to NGINX! \n This is the pod IP address: $server_addr \n \n";
                }
            }
    
        sendfile        on;
        #tcp_nopush     on;
    
        keepalive_timeout  65;
    
        #gzip  on;
    
        include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lbl2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-lbl2
  template:
    metadata:
      labels:
        app: nginx-lbl2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-conf
