apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      initContainers:
      - command:
        - sh
        - -c
        - |
          export POD_NAME
          export POD_IP
          cat <<EOF > /nginx/nginx.conf
          server {
              listen 8080;
              server_name localhost;
              location / {
                  default_type text/plain;
                  return 200 "Welcome to NGINX!\nPod Name:          $POD_NAME\nIP:                $POD_IP\nRequestPort:       \$server_port\n";
              }
          }
          EOF
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: busybox:latest
        name: render-nginx-config
        volumeMounts:
        - mountPath: /nginx
          name: nginx-config
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: nginx-config