apiVersion: v1
kind: ConfigMap
metadata:
  name: ipsec-config
data:
  start.sh: |
    #!/bin/sh
    echo "Installing Strongswan packages..."
    apt-get update && apt-get install -y strongswan strongswan-swanctl
    cp /etc/swanctl/swanctl.conf-tmp /etc/swanctl/swanctl.conf
    cp /etc/strongswan.conf-tmp /etc/strongswan.conf
    echo "Starting Strongswan..."
    ipsec start
    sleep 5
    swanctl --load-all
    echo "Defining ipsec0 interface if not existing..."
    if ip link show "ipsec0" > /dev/null 2>&1; then
        echo "Interface ipsec0 already exists."
    else
        ip link add ipsec0 type xfrm if_id 123
        ip route add 5.6.7.8/32 dev ipsec0
        ip link set ipsec0 up
        echo "Interface ipsec0 created with route to 5.6.7.8/32"
    fi
    sleep 2
    echo "We're done !"
    tail -f /dev/null
  swanctl.conf: |-
    connections {
      tunnel-accept-any {
        local_addrs  = %any
        remote_addrs = %any
        local {
          auth = psk
          id = myserver
        }
        remote {
          auth = psk
          id = myclient
        }
        children {
          net-net {
            if_id_out = 123
            if_id_in = 123
            mode = tunnel
            local_ts  = 0.0.0.0/0
            remote_ts = 0.0.0.0/0
            esp_proposals = aes128gcm128
            start_action = start
          }
        }
        version = 2
        mobike = no
        reauth_time = 10800
        proposals = aes128-sha256-modp3072
      }
    }
    secrets {
      ike-1 {
        id-1 = myserver
        id-2 = myclient
        secret = "verysecure"
      }
    }

  strongswan.conf: |-
    charon {
      install_routes = yes
      send_vendor_id = yes
      dns1 = 8.8.8.8
      dns2 = 8.8.4.4
      plugins {
        eap-dynamic {
          preferred = mschapv2, tls, md5
        }
        dhcp {
          identity_lease = yes
        }
      }

      filelog {
        charon {
            path = /var/log/charon.log
            time_format = %b %e %T
            ike_name = yes
            append = no
            default = 2
            flush_line = yes
        }
        stderr {
            ike = 2
            knl = 3
            net = 3
        }
      }
      syslog {
          identifier = charon-custom
          daemon {
          }
          auth {
              default = -1
              ike = 0
          }
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipsec-ds
spec:
  selector:
    matchLabels:
      app: strongswan
  template:
    metadata:
      labels:
        app: strongswan
    spec:
      hostNetwork: true
      containers:
      - name: strongswan
        image: ubuntu:latest
        command: ["/bin/sh"]
        args: ["/start.sh"]
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
        ports:
          - containerPort: 500
            name: vpn-isakmp
            protocol: UDP
          - containerPort: 4500
            name: vpn-ike
            protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /start.sh
          subPath: start.sh
          readOnly: true
        - name: config
          mountPath: /etc/swanctl/swanctl.conf-tmp
          subPath: swanctl.conf
        - name: config
          mountPath: /etc/strongswan.conf-tmp
          subPath: strongswan.conf
        env:
          - name: DEBIAN_FRONTEND
            value: noninteractive
      volumes:
      - name: config
        configMap:
          name: ipsec-config
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ipsec-vip
  annotations:
    metallb.universe.tf/address-pool: ipsec-external-pool
spec:
  externalTrafficPolicy: Local
  selector: 
    app: strongswan
  ports:
  - name: vpn-isakmp
    protocol: UDP
    port: 500
    targetPort: 500
  - name: vpn-ike-esp-nat-t
    protocol: UDP
    port: 4500
    targetPort: 4500
  type: LoadBalancer
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipsec-external-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.123.123.200/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-metalb-ipsec
  namespace: metallb-system
spec:
  ipAddressPools:
  - ipsec-external-pool
---



