apiVersion: v1
kind: ConfigMap
metadata:
  name: strongswan-config
  namespace: default
data:
  ipsec.conf: |
    config setup
      charondebug="ike 2, knl 2, cfg 2"

    conn mytunnel
      authby=secret
      left=%defaultroute
      leftid=@myhost
      leftsubnet=0.0.0.0/0
      right=192.168.10.201
      rightid=@myserver
      rightsubnet=192.168.10.201/32
      auto=start
  ipsec.secrets: |
    : PSK "testing123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strongswan-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strongswan
  template:
    metadata:
      labels:
        app: strongswan
    spec:
      hostNetwork: true
      initContainers:
      - name: build-strongswan
        image: alpine:edge
        command:
        - sh
        - -c
        - |
          apk --update add build-base ca-certificates curl curl-dev ip6tables iproute2 iptables-dev openssl openssl-dev
          mkdir -p /tmp/strongswan
          curl -Lo /tmp/strongswan.tar.bz2 https://download.strongswan.org/old/5.x/strongswan-5.9.13.tar.bz2
          tar --strip-components=1 -C /tmp/strongswan -xjf /tmp/strongswan.tar.bz2
          cd /tmp/strongswan
          ./configure --prefix=/usr --sysconfdir=/etc --libexecdir=/usr/lib --with-ipsecdir=/usr/lib/strongswan --enable-aesni --enable-chapoly --enable-cmd --enable-curl --enable-dhcp --enable-eap-dynamic --enable-eap-identity --enable-eap-md5 --enable-eap-mschapv2 --enable-eap-radius --enable-eap-tls --enable-farp --enable-files --enable-gcm --enable-md4 --enable-newhope --enable-ntru --enable-openssl --enable-sha3 --enable-shared --disable-aes --disable-des --disable-gmp --disable-hmac --disable-ikev1 --disable-md5 --disable-rc2 --disable-sha1 --disable-sha2 --disable-static
          make
          make install
          rm -rf /tmp/*
          apk del build-base curl-dev openssl-dev
          rm -rf /var/cache/apk/*
        volumeMounts:
        - name: strongswan-bin
          mountPath: /usr/sbin
        - name: strongswan-lib
          mountPath: /usr/lib
      containers:
      - name: strongswan
        image: alpine:edge
        command: ["/usr/sbin/ipsec"]
        args: ["start", "--nofork"]
        volumeMounts:
        - name: strongswan-bin
          mountPath: /usr/sbin
        - name: strongswan-lib
          mountPath: /usr/lib
        - name: strongswan-config
          mountPath: /etc
        ports:
        - containerPort: 500
          protocol: UDP
        - containerPort: 4500
          protocol: UDP
      volumes:
      - name: strongswan-bin
        emptyDir: {}
      - name: strongswan-lib
        emptyDir: {}
      - name: strongswan-config
        configMap:
          name: strongswan-config

