apiVersion: v1
kind: ConfigMap
metadata:
  name: ipsec-config
data:
  swanctl.conf: |-
    connections {
      tunnel-accept-any {
        local_addrs  = %any
        remote_addrs = %any
        local {
          auth = psk
          id = myserver
        }
        remote {
          auth = psk
          id = myclient
        }
        children {
          net-net {
            if_id_out = 123
            if_id_in = 123
            mode = tunnel
            local_ts  = 0.0.0.0/0
            remote_ts = 0.0.0.0/0
            esp_proposals = aes128gcm128
            start_action = start
          }
        }
        version = 2
        mobike = no
        reauth_time = 10800
        proposals = aes128-sha256-modp3072
      }
    }
    secrets {
      ike-1 {
        id-1 = myserver
        id-2 = myclient
        secret = "verysecure"
      }
    }

  strongswan.conf: |-
    charon {
      install_routes = yes
      send_vendor_id = yes
      dns1 = 8.8.8.8
      dns2 = 8.8.4.4
      plugins {
        eap-dynamic {
          preferred = mschapv2, tls, md5
        }
        dhcp {
          identity_lease = yes
        }
      }

      # two defined file loggers
      filelog {
        charon {
            # path to the log file, specify this as section name in versions prior to 5.7.0
            path = /var/log/charon.log
            # add a timestamp prefix
            time_format = %b %e %T
            # prepend connection name, simplifies grepping
            ike_name = yes
            # overwrite existing files
            append = no
            # increase default loglevel for all daemon subsystems
            default = 2
            # flush each line to disk
            flush_line = yes
        }
        stderr {
            # more detailed loglevel for a specific subsystem, overriding the
            # default loglevel.
            ike = 2
            knl = 3
            net = 3
        }
      }
      # and two loggers using syslog
      syslog {
          # prefix for each log message
          identifier = charon-custom
          # use default settings to log to the LOG_DAEMON facility
          daemon {
          }
          # very minimalistic IKE auditing logs to LOG_AUTHPRIV
          auth {
              default = -1
              ike = 0
          }
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipsec-ds
spec:
  selector:
    matchLabels:
      app: strongswan
  template:
    metadata:
      labels:
        app: strongswan
    spec:
      hostNetwork: true
      containers:
      - name: strongswan
        image: ubuntu:latest
        command: ["/bin/sh"]
        args: ["-c", "apt-get update && \
         apt-get install -y strongswan && \
         apt-get install -y strongswan-swanctl && \
         cp /etc/swanctl/swanctl.conf-tmp /etc/swanctl/swanctl.conf && \
         cp /etc/strongswan.conf-tmp /etc/strongswan.conf && \
         ipsec start && \
         sleep 5 && \
         swanctl --load-all && \
         ip link add ipsec0 type xfrm if_id 123
         ip link set ipsec0 up
         ip route add 5.6.7.8/32 dev ipsec0
         tail -f /dev/null"]
        securityContext:
          privileged: true
          runAsUser: 0
          runAsGroup: 0
        ports:
          - containerPort: 500
            name: vpn-isakmp
            protocol: UDP
          - containerPort: 4500
            name: vpn-ike
            protocol: UDP
        volumeMounts:
        - mountPath: /etc/swanctl/swanctl.conf-tmp
          name: config
          subPath: swanctl.conf
        - mountPath: /etc/strongswan.conf-tmp
          name: config
          subPath: strongswan.conf
        env:
          - name: DEBIAN_FRONTEND
            value: noninteractive
      volumes:
      - configMap:
          items:
          - key: swanctl.conf
            path: swanctl.conf
          - key: strongswan.conf
            path: strongswan.conf
          name: ipsec-config
        name: config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ipsec-vip
  annotations:
    metallb.universe.tf/address-pool: ipsec-external-pool
spec:
  externalTrafficPolicy: Local
  selector: 
    app: strongswan
  ports:
  - name: vpn-isakmp
    protocol: UDP
    port: 500
    targetPort: 500
  - name: vpn-ike-esp-nat-t
    protocol: UDP
    port: 4500
    targetPort: 4500
  type: LoadBalancer
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ipsec-external-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.123.123.200/32
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-metalb-ipsec
  namespace: metallb-system
spec:
  ipAddressPools:
  - ipsec-external-pool
---



