apiVersion: v1
kind: ConfigMap
metadata:
  name: strongswan-config
  namespace: default
data:
  ipsec.conf: |
    config setup
      charondebug="ike 2, knl 2, cfg 2"

    conn mytunnel
      authby=secret
      left=%defaultroute
      leftid=@myhost
      leftsubnet=0.0.0.0/0
      right=192.168.10.201
      rightid=@myserver
      rightsubnet=192.168.10.201/32
      auto=start
  ipsec.secrets: |
    : PSK "testing123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strongswan-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strongswan
  template:
    metadata:
      labels:
        app: strongswan
    spec:
      hostNetwork: true
      initContainers:
      - name: build-strongswan
        image: alpine:edge
        command:
        - sh
        - -c
        - |
          apk add --no-cache strongswan openssl
          rm -rf /var/cache/apk/*
          echo "done with install ..."
        volumeMounts:
        - name: strongswan-bin
          mountPath: /usr/sbin
        - name: strongswan-lib
          mountPath: /usr/lib
      containers:
      - name: strongswan
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        image: alpine:edge
        command: ["/usr/sbin/ipsec"]
        args: ["start", "--nofork"]
        volumeMounts:
        - name: strongswan-bin
          mountPath: /usr/sbin
        - name: strongswan-lib
          mountPath: /usr/lib
        - name: strongswan-config
          mountPath: /etc
        ports:
        - containerPort: 500
          protocol: UDP
        - containerPort: 4500
          protocol: UDP
      volumes:
      - name: strongswan-bin
        emptyDir: {}
      - name: strongswan-lib
        emptyDir: {}
      - name: strongswan-config
        configMap:
          name: strongswan-config

